version: '3.8'

services:
  app:
    build: .
    container_name: optimas-nest-app
    ports:
      - '3000:3001'
    volumes:
      - .:/app
      - /app/node_modules
      - sqlite_data:/app/prisma
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: optimas-redis
    restart: always
    ports:
      - '6379:6379'

volumes:
  sqlite_data:
